name = "lean_problem_solving"
version = "0.1.0"
defaultTargets = ["ProblemSolving", "hello_world", "a_plus_b", "sorting", "mispelling", "mispelling2"]
testDriver = "example_test"

[[lean_lib]]
name = "ProblemSolving"

[[lean_exe]]
name = "hello_world"
root = "examples.HelloWorld"

[[lean_exe]]
name = "a_plus_b"
root = "examples.APlusB"

[[lean_exe]]
name = "sorting"
root = "examples.Sorting"

[[lean_exe]]
name = "mispelling"
root = "examples.Mispelling"

[[lean_exe]]
name = "mispelling2"
root = "examples.Mispelling2"

[[lean_exe]]
name = "example_test"
root = "examples.tests.ExampleTest"
needs = ["hello_world", "a_plus_b", "sorting", "mispelling", "mispelling2"]
