name = "lean_problem_solving"
version = "0.1.0"
defaultTargets = ["ProblemSolving"]

[[lean_lib]]
name = "ProblemSolving"

[[lean_exe]]
name = "helloworld"
srcDir = "examples/helloworld"
root = "HelloWorld"
